# Generated by Django 3.2.25 on 2024-11-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=300, verbose_name='Content'),
        ),
    ]
