# Generated by Django 3.2.25 on 2024-11-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20241101_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight (kg)'),
        ),
    ]
